<?php

session_start();
$apiKey = "rzp_test_rnyrWCRASjyyeC";
include('appdet.php');

?>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Payments</title>
    <link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="pay.css" />
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"
    ></script>
    <script type="text/javascript" src="pay.js"></script>
    <style>
      #razor{
        margin : 1rem;
      }
    </style>

  </head>
  <body  class="snippet-body">
    <div class="card card0">
      <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
          <div class="sidebar-heading pt-5 pb-4">
            <strong>PAY WITH</strong>
          </div>
          <div class="list-group list-group-flush">
            <a
              data-toggle="tab"
              href="#menu1"
              id="tab1"
              class="tabs list-group-item bg-light"
            >
              <div class="list-div my-2">
                <div class="fa fa-home"></div>
                &nbsp;&nbsp; Bank
              </div>
            </a>
            <a
              data-toggle="tab"
              href="#menu2"
              id="tab2"
              class="tabs list-group-item active1"
            >
              <div class="list-div my-2">
                <div class="fa fa-credit-card"></div>
                &nbsp;&nbsp; Card
              </div>
            </a>
            <a
              data-toggle="tab"
              href="#menu3"
              id="tab3"
              class="tabs list-group-item bg-light"
            >
              <div class="list-div my-2">
                <div class="fa fa-qrcode"></div>
                &nbsp;&nbsp;&nbsp; Visa QR <span id="new-label">NEW</span>
              </div>
            </a>
            <!-- <a
              data-toggle="tab"
              href="#menu4"
              id="tab4"
              class="tabs list-group-item bg-light"
            > -->
            <!-- <div class="list-div my-2"> -->
                <!-- <div class="fa fa-qrcode"></div> -->
                <!-- &nbsp;&nbsp;&nbsp; Pay With RazorPay  -->
                <form id ="razorForm" action="" method="POST">
                
                <?php foreach ($appdetails as $appdetail) { ?>
                         <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys data-amount="<?php echo 1 * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35. data-currency="INR" //You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account data-id="<?php echo 'OID' . rand(10, 100) . 'END'; ?>" //Replace with the order_id generated by you in the backend. data-buttonId="dan" data-buttontext="Pay with Razorpay" data-name="IREU" data-description="IREU Education" data-image="https://upload.wikimedia.org/wikipedia/commons/0/0a/JGI-logo.png" data-prefill.name="<?php echo $appdetail['firstname'] . ' ' . $appdetail['lastname']; ?>" data-prefill.email="<?php echo $appdetail['email']; ?>" data-prefill.contact="<?php echo $appdetail['registered_mob_num']; ?>" data-theme.color="#F37254">
                          </script>
                          <!-- <input type="hidden" custom="Hidden Element" name="hidden"> -->
                          <!-- $_POST['amount'] -->
                          <?php } ?>
                       <script>
                     $("#razorForm input[type='submit']").attr('id', 'razor');
                       $("#razor").last().addClass( "btn btn-success" );
                       </script>
                
                 </form>  
                 <!-- </div> -->
            <!-- </a> -->
          </div>
        </div>
        <!-- Page Content -->
        <div id="page-content-wrapper">
          <div class="row pt-3" id="border-btm">
            <div class="col-4">
              <button class="btn btn-success mt-4 ml-3 mb-3" id="menu-toggle">
                <div class="bar4"></div>
                <div class="bar4"></div>
                <div class="bar4"></div>
              </button>
            </div>
            <div class="col-8">
              <div class="row justify-content-right">
                <div class="col-12">
                  <p class="mb-0 mr-4 mt-4 text-right">customer@email.com</p>
                </div>
              </div>
              <div class="row justify-content-right">
                <div class="col-12">
                  <p class="mb-0 mr-4 text-right">
                    Pay <span class="top-highlight">$ 100</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="text-center" id="test">Pay</div>
          </div>
          <div class="tab-content">
            <div id="menu1" class="tab-pane">
              <div class="row justify-content-center">
                <div class="col-11">
                  <div class="form-card">
                    <h3 class="mt-0 text-center">
                      Enter bank details to pay
                    </h3>
                    <form>
                      <div class="row">
                        <div class="col-12">
                          <div class="input-group">
                            <input
                              type="text"
                              id="bk_nm"
                              placeholder="BBB Bank"
                            />
                            <label>BANK NAME</label>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-12">
                          <div class="input-group">
                            <input
                              type="text"
                              name="ben_nm"
                              id="ben-nm"
                              placeholder="John Smith"
                            />
                            <label>BENEFICIARY NAME</label>
                          </div>
                        </div>
                        <div class="col-12">
                          <div class="input-group">
                            <input
                              type="text"
                              name="scode"
                              placeholder="ABCDAB1S"
                              class="placeicon"
                              minlength="8"
                              maxlength="11"
                            />
                            <label>SWIFT CODE</label>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <input
                            type="submit"
                            value="Pay $ 100"
                            class="btn btn-success placeicon"
                          />
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <p class="text-center mb-5" id="below-btn">
                            <a href="#">Use a test card</a>
                          </p>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <div id="menu2" class="tab-pane in active">
              <div class="row justify-content-center">
                <div class="col-11">
                  <div class="form-card">
                    <h3 class="mt-0 mb-4 text-center">
                      Enter your card details to pay
                    </h3>
                    <form>
                      <div class="row">
                        <div class="col-12">
                          <div class="input-group">
                            <input
                              type="text"
                              id="cr_no"
                              placeholder="0000 0000 0000 0000"
                              minlength="19"
                              maxlength="19"
                            />
                            <label>CARD NUMBER</label>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-6">
                          <div class="input-group">
                            <input
                              type="text"
                              name="exp"
                              id="exp"
                              placeholder="MM/YY"
                              minlength="5"
                              maxlength="5"
                            />
                            <label>CARD EXPIRY</label>
                          </div>
                        </div>
                        <div class="col-6">
                          <div class="input-group">
                            <input
                              type="password"
                              name="cvcpwd"
                              placeholder="&#9679;&#9679;&#9679;"
                              class="placeicon"
                              minlength="3"
                              maxlength="3"
                            />
                            <label>CVV</label>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <input
                            type="submit"
                            value="Pay $ 100"
                            class="btn btn-success placeicon"
                          />
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <p class="text-center mb-5" id="below-btn">
                            <a href="#">Use a test card</a>
                          </p>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <div id="menu3" class="tab-pane">
              <div class="row justify-content-center">
                <div class="col-11">
                  <h3 class="mt-0 mb-4 text-center">Scan the QR code to pay</h3>
                  <div class="row justify-content-center">
                    <div id="qr">
                      <img
                        src="https://i.imgur.com/DD4Npfw.jpg"
                        width="200px"
                        height="200px"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div id="menu4" class="tab-pane">
              <div class="row justify-content-center">
                <div class="col-11">
                                          
                   </div>
              </div>
            </div>
          </div>
          <!-- tab content  -->
        </div>
      </div>
    </div>
  </body>
</html>
